config/routes.rb
Blogger::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #get "articles/index"
  root 'articles#index'

  resources :articles
 
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	#validates :title, presence: true 
	#validates :body, presence: true 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :author_name, presence: true
  validates :body, length: { minimum: 2, maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  


  def index
  	@articles = Article.all
  end
  
  def show
  	@article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
    @article.save

    flash.notice = "Article '#{@article.title}' Was succesfully created!"

    redirect_to article_path(@article)
  end

  def edit
  	@article = Article.find(params[:id])
  end

  def update
  	@article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

  def destroy
  	@article = Article.find(params[:id]).destroy
  	
  	flash.notice = "Article '#{@article.title}' Was deleted!"

 	redirect_to articles_index_path(@articles)
  end

  private

  def article_params
  	params.require(:article).permit(:title,:body, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
  @comment = Comment.new(comment_params)
  @comment.article_id = params[:article_id]

  @comment.save

  redirect_to article_path(@comment.article)
end

def comment_params
  params.require(:comment).permit(:author_name, :body)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4><p>Posted <%= time_ago_in_words(comment.created_at) %> ago</p>

  <p class="comment"><%= comment.body %></p>
  
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br />
  <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

<%= link_to "<< back", articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
<p><%= @article.body %></p>
<%= link_to "<- back", articles_path %>

<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}
 %>
 <%= link_to "edit", edit_article_path(@article) %>
 <h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'comments/form' %>
<%= render partial: 'articles/comment', collection: @article.comments %>

app/views/comments/_form.html.erb
<h3>New Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, 'Your name' %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, 'Your Comment' %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger | Michal Staniszewski</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="flash"><%= flash.notice %></p>

</body>
</html>